require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
    NewCops: enable

Style/ModuleFunction:
  EnforcedStyle: extend_self
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  CountKeywordArgs: false