name: build-test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [2.5, 2.6, 2.7, head]

    steps:
    - uses: actions/checkout@v2
    - name: use-ruby ${{ matrix.version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.version }}
    - run: bundle install
    - run: bundle exec rake
